---
  # This YAML configuration specifies a server with two volumes and two users
  server:
    instance_type: t2.micro
    ami_type: amzn2
    architecture: x86_64
    root_device_type: ebs
    virtualization_type: hvm
    min_count: 1
    max_count: 1
    volumes:
      - device: /dev/xvda
        size_gb: 10
        type: gp2
        mount: /
      - device: /dev/xvdg
        size_gb: 100
        type: gp2
        mount: /data
    users:
      - login: user1
      - login: user2
